version: '1.0'
name: master-pipeline
displayName: MasterPipeline
stages:
  - stage:
    name: build
    displayName: 构建
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        # JDK 21 对应云效的 21 版本
        jdkVersion: 21
        mavenVersion: 3.6.3
        commands:
          - mvn -B clean package -Dmaven.test.skip=true
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./server/target/kkFileView-*.tar.gz
              - ./Dockerfile
      - step: build@china_aliyun_docker
        name: build_docker
        displayName: Docker 构建推送
        # 引用上一步的构建产物
        input:
          - BUILD_ARTIFACT
        dockerfilePath: Dockerfile
        contextPath: .
        repository: crpi-wj9nu4mw74znjcbt.cn-shenzhen.personal.cr.aliyuncs.com/resource-pool/aireach-resource
        tag: file-preview-${DATETIME}
        region: cn-shenzhen
triggers:
  push:
    branches:
      include:
        - master
